defaults: &defaults
  adapter: postgresql
  username: <%= ENV['USER'] || "postgres" %>
  password:
  database: infoeducatie_<%= Rails.env %>
  min_messages: ERROR
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *defaults

staging:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
